apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ofnir
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: |
    ofnir.dev tenant workloads. No cluster-scoped resources.
    Namespace prefix `ofnir-*` reserved.
  sourceRepos:
    - https://github.com/urosevicvuk/ykube
  destinations:
    - namespace: ofnir
      server: https://kubernetes.default.svc
    - namespace: 'ofnir-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
