apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg

resources:
  - namespace.yaml

helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.io/charts/
    version: 0.28.0  # renovate: depName=cloudnative-pg/cloudnative-pg
    releaseName: cloudnative-pg
    namespace: cloudnative-pg
    valuesFile: values.yaml
    includeCRDs: true
