apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden

resources:
  - namespace.yaml
  - cnpg-cluster.yaml
  - secrets.yaml
  - httproute.yaml

helmCharts:
  - name: vaultwarden
    repo: https://guerzon.github.io/vaultwarden
    version: 0.39.1  # renovate: depName=vaultwarden registryUrl=https://guerzon.github.io/vaultwarden
    releaseName: vaultwarden
    namespace: vaultwarden
    valuesFile: values.yaml
