apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: vaultwarden
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    requests.storage: 20Gi
    persistentvolumeclaims: "10"
    pods: "20"
