apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secrets
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-secrets
  data:
    - secretKey: secret-key
      remoteRef:
        key: secret/harbor
        property: secret-key
    - secretKey: admin-password
      remoteRef:
        key: secret/harbor
        property: admin-password
