apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: morel-data
  namespace: apps-external
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
