apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateways/cloudflare.yaml
  - http-routes/argocd.yaml
  - http-routes/vault.yaml
  - http-routes/grafana.yaml
  - http-routes/excalidraw.yaml
  - http-routes/opencloud.yaml
  - http-routes/stirling-pdf.yaml
  - http-routes/gitlab.yaml
  - http-routes/gitlab-registry.yaml
  - http-routes/harbor.yaml
  - http-routes/searxng.yaml
  - http-routes/authelia.yaml
  - http-routes/pocket-id.yaml
  - http-routes/hubble.yaml
