# TODO: configure cloudnative-pg
# This is a placeholder. Wire up the helm chart + values + per-app resources here.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg

resources:
  - namespace.yaml
