apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - databases/gitlab/cluster.yaml
  - databases/gitlab/credentials.yaml
  - databases/harbor/cluster.yaml
  - databases/harbor/credentials.yaml
  - databases/authelia/cluster.yaml
  - databases/authelia/credentials.yaml
