apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/urosevicvuk/ykube.git
    targetRevision: HEAD
    path: security/authelia/environments/prod
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
