apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.17.13
      helm:
        valueFiles:
          - $ykube/networking/cilium/environments/prod/values.yaml
    - repoURL: https://github.com/urosevicvuk/ykube.git
      targetRevision: HEAD
      ref: ykube
    - repoURL: https://github.com/urosevicvuk/ykube.git
      targetRevision: HEAD
      path: networking/cilium/environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipSchemaValidation=true
