apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana-operator
      targetRevision: v5.22.2
      helm:
        valueFiles:
          - $ykube/observability/grafana/environments/prod/values.yaml
    - repoURL: https://github.com/urosevicvuk/ykube.git
      targetRevision: HEAD
      ref: ykube
    - repoURL: https://github.com/urosevicvuk/ykube.git
      targetRevision: HEAD
      path: observability/grafana/environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipSchemaValidation=true
