apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.18.2
      helm:
        valueFiles:
          - $ykube/storage/harbor/environments/prod/values.yaml
    - repoURL: https://github.com/urosevicvuk/ykube.git
      targetRevision: HEAD
      ref: ykube
    - repoURL: https://github.com/urosevicvuk/ykube.git
      targetRevision: HEAD
      path: storage/harbor/environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
