apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
  data:
    - secretKey: session.encryption.key
      remoteRef:
        key: secret/authelia
        property: session-encryption-key
    - secretKey: storage.encryption.key
      remoteRef:
        key: secret/authelia
        property: storage-encryption-key
    - secretKey: identity_providers.oidc.hmac.key
      remoteRef:
        key: secret/authelia
        property: hmac-secret
    - secretKey: hmac-secret
      remoteRef:
        key: secret/authelia
        property: hmac-secret
