apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-users
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authelia-users
  data:
    - secretKey: users_database.yml
      remoteRef:
        key: secret/authelia
        property: users-database
