---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-creds
  namespace: apps-external
spec:
  encryptedData:
    .dockerconfigjson: AgBKlgJ8oXWWoqJOU+qi9ovZrNxSlc1pyVeR7WwAiYgnKfORsBGdcSCT6V/OFVzliWYVl8QM90dmCWiwMIiHzRxyaSuHR6g89lea6Qr6R8bFzGd1/fvKBcVP/cMPoPFlEG13jFTrLCH/5FnDt9cLUxTIiVeeYU7wsN8VrvPMGqFmVaHtaDHo54FZ3bBnlAnK+fL8K5zaPOHK+U5c2zSyeNioT9V6DXKHosJT1I1WQFpl/O4nAgcwFlrFz6ayIJLswciNvZJ8MXID6vR4s9fm4zugJiAdsH23aNmvt5SXKiMPaMX1pRxZUgVRgWE8OZ3t9T2DJwDe4TzUIPPXrVLF8xgkzIpfQ5jv4KQi6mfYADxGEHiI2mzn1O4ULxqK5+pdZwa+NHManGu3OBhVam4Vu9b9xJKevB953UtgkHlU0stiKizPeAftvA9wnjAu1iaMPahaXrxhc+KNlwIhjwK4/kLXZD5z4+mPbf+5TgtdcJYyCW6WHiD5CPijeIGWuXNSKm9b40ZBBzYIDK/vLvr9PQ74hEKr0rdxOdU13BbSCgOdXTM3oTsrypu/WQSwVCGpLv7r7whFwtf2Lm/j1qFQ2mZRL87EwtiE4T9cQwbc4f+UNkkaf7Af/xoCU3XByWTP48IZ0JB53VdPYRGe7crBCJIA/jYF9OEIjHcL7ReL6r5xBBzz9dULG7/6/7P50z43rAe1Jv6IP5RNFSfCRhN7WHoOSq3J3C3rVRn4H1SA0MD9SObGE37nqBO26HtwCB7wRjTeJVfwnfmJ9mEGJOyGDV+g67MM5DnUe5VzFniVQIW/FC4YSqtaavBDL/fmGEsCFTUMhBGJNTtFrq9j5nZ0eSNFLfEeKCYyczSmTazkjZYqpJX33luIW5sVhsN62B9fb+hfqRkaaKwO2hr1BGrbC5LsIHT7Qk7bhO5ZzZtQ1pRetiJmLHyWq4Se+wQ0x5AO5Al+hXW+5ZITkUfhSYLqu6V6kw==
  template:
    metadata:
      name: gitlab-registry-creds
      namespace: apps-external
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: morel-smtp-creds
  namespace: apps-external
spec:
  encryptedData:
    smtp-pass: AgARwTLrGQbLYCLlAx/YswTCiIY+MqUV3oXrVFfKaSbbFn/Ae4rwa0O1iAvz5st2os69WrUS7MO5FKTyVnB0k9my00B6JWZ/hbvLhYq2F0cmPZ2NVqkYSwrT4IPVR95DCxdrdy9LOnOh5ZXtLGya0zqX1KXUJ+/FOWJjj5/ZgQjFJMbkeLTfz4CvcXvSb+DzEdGvQQlb8K7fQ4d7PjIiDl1FJlob3cbHjjB4a+Q40dwY2H1t5SNWyDDNIKFemm71kzd1q6+m2Ffnjpui+rS/DbBeAqVu3teXCPOQ7l+XcKGqWoXoLZ7XEMUHT86Sd0KjDOZDHWtUKfp9A1TryCeI2flTGKWE0jtiHpi1610ouXQD7cx2qSCXA5WPpc+p3Hn/K5ELwEQcgGLyJx4YUZAXJWygkOAzVJDXL+P9f0q7nGo9CJ9+/AUpfPcSBmLEx6is5CSVoYT2CycSYP865tSJXg076LkV137pm8Gws/Chjyc7XXaejjvP/7S1xSgQD0RPN91jnmf5Uy9eZXPWPi09BvlK4feTs9zFjwEGJuQASqhH+XY1N7tOkQUaFhNq7snG3yNe7HleQvk6jUYDs/bX2ays7JmIj4D1lQoKz1hm66dqWTCV5kWWcXFSWiYbSxVpmOckPPxrvfGLzOpQa9iT9+p4Y7mUywxqTzE3wcY+lCbC9wpua5VrX6siyV+V1rQgIZS09k0RhKXg9OCQpuGJU1Uk
    smtp-user: AgAarxEwZhEF2jfwTN7XcuKG1OJhjZ9KVX/ycl9XsAlksvi+K4Np9mGRGsPJyepE0IIBRGVlFwbs1YVQ3Y/6xQIVMGXYVFUFzdHV7pKS7s0NUKkvW9L9n5dUNz2AAM0Xhepj8TZsGnCKAJ1l1HJA8H0FtJlorJZgqyJCTLGlSpmlnKfvI9mo+ybzRhcHsizi9bz4tLRIg6qzSk5i5TrEm51s6t/1/0IbVlwdJqj9nqiEOVoXKJiVcJaN5ygiUej3nSStrF+UMoMpt8yFbEwK5coil0KVDgLJmaKI5JeURViWukpjc5tA3TydBANydpn/5FilAQL2w8D87PGRDszoQYUCYgfcWwnecbqEN7krwo+bJ1gSVMuC8rB0nJgxr67bC7neOLvrXccgLozld/fOmkNLSFh/L2LSfSEoD0ruGjzWQSpAw/mD/Qk9qtB9zk25Sygkp+emrFZunieSPxWdyRkqrIBu4rQ6q3P4viAslWi8K9rtPLzjcgI4Zle4IyctVDoMN2PSAh6A3DGt1UWRqkSCm4BCvURlDdViPcb/wNgIq5PqGJpqK9YK+FXNB9paTSwwrwyHMt+jDiOA6puwYSiCujC5G+wvw0YzTMRNGAG0XZ1RhHK93VEAqYTRd3Cgoz8u8qycuaccHarVCsoXnyUgu0I1/pa7dco9f2S4IaJUEBqMLAKNWLo9Q0xjhVi3X7rg92xYj8QvUemR0n4HF1YCf1hp
  template:
    metadata:
      name: morel-smtp-creds
      namespace: apps-external
