apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/urosevicvuk/ykube.git
    targetRevision: HEAD
    path: infrastructure/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
