apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-db-credentials
  namespace: gitlab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-db-credentials
  data:
    - secretKey: password
      remoteRef:
        key: secret/cloudnative-pg/gitlab
        property: password
    - secretKey: username
      remoteRef:
        key: secret/cloudnative-pg/gitlab
        property: username
