apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-raf-project-com-tls
  namespace: system-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: wildcard-raf-project-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.raf-project.com"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: system-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    argocd.argoproj.io/sync-wave: "2"
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      port: 8000
      protocol: HTTP
      hostname: "*.urosevicvuk.dev"
      allowedRoutes:
        namespaces:
          from: All
    - name: websecure
      port: 8443
      protocol: HTTPS
      hostname: "*.urosevicvuk.dev"
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-urosevicvuk-dev-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
    - name: web-raf
      port: 8000
      protocol: HTTP
      hostname: "*.raf-project.com"
      allowedRoutes:
        namespaces:
          from: All
    - name: websecure-raf
      port: 8443
      protocol: HTTPS
      hostname: "*.raf-project.com"
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-raf-project-com-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
