apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-pg
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  storage:
    size: 5Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  monitoring:
    enablePodMonitor: true
