apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cosign-key-pair
  namespace: argo-workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cosign-key-pair
  data:
    - secretKey: cosign.key
      remoteRef:
        key: secret/cosign
        property: private-key
    - secretKey: cosign.pub
      remoteRef:
        key: secret/cosign
        property: public-key
    - secretKey: cosign.password
      remoteRef:
        key: secret/cosign
        property: password
