apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-dagger-robot-secret
  namespace: argo-workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-dagger-robot-secret
  data:
    - secretKey: password
      remoteRef:
        key: secret/harbor/dagger-robot-secret
        property: password
