apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: twenty-crm
  namespace: ofnir-twenty-crm
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  parentRefs:
    - name: gateway-internal
      namespace: envoy-gateway-system
  hostnames:
    - crm.ofnir.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: twenty-server
          port: 3000
