apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twenty-crm

resources:
  - namespace.yaml
  - cnpg-cluster.yaml
  - secrets.yaml
  - redis.yaml
  - pvcs.yaml
  - deployment.yaml
  - worker.yaml
  - httproute.yaml
