apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-ngx-pg
  namespace: paperless-ngx
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  storage:
    size: 5Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  monitoring:
    enablePodMonitor: true
