apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-encryption-key
  namespace: pocket-id
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pocket-id-encryption-key
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: secret/pocket-id
        property: encryption-key
