---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: networking
spec:
  encryptedData:
    tunnel-token: AgCdopIFVfYFMETVwZ1r427N9WN4aZcamd+SQPMrmCaF7PycpdggzEiOyu2kfvMuuxvJXrgOJ6SrEd5ajW9YTXNXdcbrcvwTfE2lWvj7gAL5vTSaSM8qSK+Y9Iy6RGxmpNAhBybjxLUk6wmrvT97wM7SmhM3ITt8w65jGF8J8I8sBra3YLSsVavKObrOnNEFOWq6TkTtSiOxB6+htDXTu8TISY41qbKd/PwbTFHMmArpQsOaNiTMRxRyXAbFZTpeLOBLlyL5IlkxVqjJY3uJyGGWO4433kKuePXzxvz1R/7+41PiGXXGvOml4sZQLBNi3oRKO/JZ0cTgLMyV3N/Y3q37xkJ9j0YyN+/fwTafn+NyGDsL67UGi+TdNmfvzsIVgVWmptqNey9jf8cy4oO8kRg2vG9igVTrJm+mKcl3WlfeeTS6UMQC1yESQlrwNH6jGl1S52ugvVqndxC/vRfRvBCszpz7xbic/1QDvm/kTa2Mju4WJMvPoel8mlMISsvpmdhL6VSWXZwetGhLyCoKBcS4NQwvASOZ0I5RgfRND+9bvqukVJjG2i1vqSegywwAIG5P6Bs+coMDR3MCjT+nCaXCljOnapZoYgyEITbLvTmnCdNaMUITbT+d88sKo7LyNB3QtLrmznQdXyHisoVOvcC78X+MU4b9ezvRL39dUyyOyOgXI/91j98/m0eLndlf03z11bPWQ2Q/7QvWhXfxx/gzE3g8WxaSN74MrBDQJgHRwb6P6Jikf5uvp5EggwJm94IgvVruoLumt2PiegAmOGzjF/4wRDQP+tsbshkSw/CYBYrlHrOgdRrhvlbTptX6JVY3tGfIl0bkEyFMPP6eWFUgUZnV8yb9xyal6DLGtbIa+8ma0TSp6wWYXGEBIW13YCf5gjdiF583Z5mQZKZbvMvocM32MYXtQNrJHCaYH0HHFdfT5IvgdTJK
  template:
    metadata:
      name: cloudflared-credentials
      namespace: networking
