apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab-postgres
  namespace: system-cicd
  labels:
    app: gitlab-postgres
spec:
  serviceName: gitlab-postgres
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-postgres
  template:
    metadata:
      labels:
        app: gitlab-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.8-alpine
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - gitlab
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - gitlab
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: POSTGRES_DB
              value: gitlabhq_production
            - name: POSTGRES_USER
              value: gitlab
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitlab-db-credentials
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: init-scripts
          configMap:
            name: gitlab-postgres-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-postgres
  namespace: system-cicd
spec:
  selector:
    app: gitlab-postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-postgres-init
  namespace: system-cicd
data:
  init-extensions.sql: |
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    CREATE EXTENSION IF NOT EXISTS btree_gist;
