---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openproject-postgresql-secrets
  namespace: apps-external
spec:
  encryptedData:
    password: AgCmx93ACLnRHDoCFGHQR5xh10mszn3k26clm2GI5UlRtib61ul+Jmod/pTACdvArUigrA2ykF/puHZVz6GP7mUIuK7lapIB5afe9LTSeKjpMyZLABEcfTZ62LDaxLpVJzRc2MckqNNx54O0s14S9Mg99eE9wqViLoq0JRZ+WUoKjeRSSH6WyRQVwgLAVTl7uGUvA8KZ2PPEHFuZEvKmLqbCMtOYrpZUGKbKpSXzlC7rPPQCrhxLXsdnNvXWHMKo69wx7pA6rYkqbXOdSolVs8gr2ivlxz4V4+IZz16XSodKNl1E0STrfwrlxXITA9PXX8szgxPSwfN+fTisijI9pmBVKMpuKabiPyhJgH5/f/SQPQMPM5OVYyXHLQSGH0/KrSLoeCapsnDJ/tAPhMIRoe8Hqgism5PmXkj0e8r3cz5iaqTYQX+MQDbBDJALZq383O85txsY9r6Z5uJMSR6RypOHgZoDP5osKM2ZuG6Nr6pudUKVXCIQRi9DdG6bBCkToWACc5T9FPlAY09xOo8G9qJMQK6zn573rKmFq+XXEFkKFRui9BbrSYNpGYhXvjQ44LUd9tTUlwjh6XaNrE2fDnB8bNg/NbIjDV2kxUgHBndZT9J/mDR2yWJlJ1kpAQPMx3ghIMnPkqo5GARGTpGRg5yTBt1cEgy/fjOIPHRGwDuZsZgT0GbApvGiUoCYBC7m10hUqfMSIwu1cjtB+00=
    postgres-password: AgCUmgkzEuAMnOxL7deZYpTf+7mFZf1OV6p4H63hkbhgbn4GE7yCyMcXXH+Ng6FDKq9tIzPHUoZLlKOVUWPM+7it7i8a95iwI/h2Bb7+SP1U+pNSiLpwd7ObwpY6yK11GhbiseJ0BEg+MHhe2sfm0B90sHpRT+TgcN73mxchBUJ5OqB0tE4+9KqvusgFxSIyGu56tKQcLEHk+GmpVWFBdOszoUfN42usUdlTk/hjZRorMaM7qXmnzMrsCjo2NWyIBtBuoQ3WyxUrCnWKh8aYgZf7N4PgYa566UIEA01rC3DWmRzuD2eSa3yLz45DC8aPMOYaLIttBBwhFcOB17X4u6sasSyjAdbsNZ9x9u8eUeNUxplt+qbWwavSA+hGqvMxFVtKStKUTZJYKxNMjxNw6QbEzUolPTG0BRYnwzoPUdHTv75f5Ep3AwBPBad1c5ABiqAdDBEYA6ZZWnPPLu4tJ6dG3xEvgveLDQfp9fouSaKEFXHioRAOCBNgAkVD2hhDCQkMSh/E1xuC3jRLHkeTi4L2NaopnlAcEABxdcWs0Kg2cC23i7yGrq7Zi7XFqBy/4IcuvsORBW77g6qjrtA7krotK3yOyBwEONTPmWabvL4PpxDjLrxY7nUS7O7mWVIGfIRItICt07kKUxd7mWUu15qZ7GUeDLtb+aIfp2txHHWHlW5RxDFs1Koat3+Cx3nILVMCWFZN0c67Xs6Vd6w=
  template:
    metadata:
      name: openproject-postgresql-secrets
      namespace: apps-external
