# OpenProject Helm values
# Chart: openproject v13.3.0
# Full reference: https://github.com/opf/helm-charts/blob/main/charts/openproject/values.yaml

openproject:
  host: "openproject.raf-project.com"
  https: true

ingress:
  enabled: false

#Kyverno policies
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "4"
    memory: "4Gi"

postgresql:
  auth:
    existingSecret: openproject-postgresql-secrets
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  primary:
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "512Mi"

memcached:
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

seederJob:
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "1Gi"

#Storage
persistence:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  size: 15Gi
