apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret
  namespace: searxng
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: searxng-secret
  data:
    - secretKey: secret-key
      remoteRef:
        key: secret/searxng
        property: secret-key
