apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-defaults
  namespace: actualbudget
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 50m
        memory: 128Mi
