apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openproject
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.openproject.org
      chart: openproject
      targetRevision: "13.3.0"
      helm:
        valueFiles:
          - $values/apps-external/openproject/values.yaml

    - repoURL: https://github.com/urosevicvuk/ykube.git
      targetRevision: HEAD
      ref: values

    - repoURL: https://github.com/urosevicvuk/ykube.git
      targetRevision: HEAD
      path: apps-external/openproject
      directory:
        include: "{route.yaml,secrets.yaml}"

  destination:
    server: https://kubernetes.default.svc
    namespace: apps-external
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
