---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-data
  namespace: ofnir-actualbudget
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
