apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: ofnir-actualbudget
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 2Gi
    requests.storage: 10Gi
    persistentvolumeclaims: "5"
    pods: "10"
