apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/urosevicvuk/ykube.git
    targetRevision: HEAD
    path: system-cicd/gitlab
    directory:
      include: "{postgres.yaml,redis.yaml,secrets.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: system-cicd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
