apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/urosevicvuk/ykube.git
    targetRevision: HEAD
    path: apps-external/stirling-pdf
    directory:
      include: '{stirling-pdf-route.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-external
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
