apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
      chart: stirling-pdf-chart
      targetRevision: "3.1.0"
      helm:
        valueFiles:
          - $values/apps-external/stirling-pdf/values.yaml
    - repoURL: https://github.com/urosevicvuk/ykube.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/urosevicvuk/ykube.git
      targetRevision: HEAD
      path: apps-external/stirling-pdf
      directory:
        include: '{stirling-pdf-route.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-external
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
