---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: system-ingress
spec:
  encryptedData:
    credentials.json: AgBXcGb7QZ+SnRYt5dzneQEPDsQudVhWMfLQhFrHiOyadVcZ8XRfeuuZg8Ka9GATDzAH8PGrK1J3WpZ0i21N1XUE3945lsW372BMvHp9+ZN0JtcpdPmrY48xu3Qb12upgVxJhMpbKb7tzuqbqI5iXkxZn7jUI5Sq9y5G4cIq1nRSmgA/VGOVdIRuy6xPRnqdKc6rU875qPUVBMjKMrRnDVQzNj1kapa4CyfmuUZCR1hPC1waSTV9zDfmIFl8pUv8+f0fdDCydkEpeFy6mnWSBjAN6uP9BMtkc0mW08HreF+5h2zR1vqy7RNkFy9+8eNhMtwBjFNe5ceaOKwYomrOtU4RMgjOTM/y4yUvrPgs99JIW34jXGNvPmJPP9V9guovU3xiyfSRuwxtKuPzXiWVniZdW5/odXXYmtTPcUFpcfCzvWuxpBXX3R5NdgC+gidOPbS7yhlMFvsg7guWeq4vRxp4uE+FhSLrtrxSc2I/wH88aUX0j9M1+uMyRCUZxL3dJNPxi+s0VkORfJajyCXQLoaknJACM10cmsCyC0lF0wEQqFHt4dh8tskf64QYyADycRVQizB0Sy9DCEemJsuT6WV684L1Nvzn1sJLV5Q67cCGInl59H5OVsTv+QSUqyLEZtkopzueJPfFSsYy6QvtB+gxlyreAyDJ60YG3dS18b8PeRQ8wX92BzEQDXXPJqwaMfKjCAIKEZud02INFHsJEW4fDj64tF3rkxI4etrh4dffbw1xSkdSbAFn59949JgrZiEHsy7RYA+xJEunKxpbVfb4R03klWn6yvxsKZhAGG/bhCiVT8ETqkBAdUf7OPJ6pWs0M1bB2lGrYHn53izNmwyWeT1M38ZUmtw6WzetvnvSQr0Oen4eRXbxGFn7RWFngK3lux+OlFTWwNRZ56OXOy5hI7EeXQkE9Vhrj1ZIZzAy
  template:
    metadata:
      name: cloudflared-credentials
      namespace: system-ingress
    type: Opaque
