apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: ghostfolio
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    requests.storage: 10Gi
    persistentvolumeclaims: "5"
    pods: "10"
