apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - namespace.yaml
  - secrets.yaml

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.21.1  # renovate: depName=external-dns/external-dns
    releaseName: external-dns
    namespace: external-dns
    valuesFile: values.yaml
    includeCRDs: true
