apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-defaults
  namespace: stirling-pdf
spec:
  limits:
    - type: Container
      default:
        cpu: "2"
        memory: 2Gi
      defaultRequest:
        cpu: 200m
        memory: 512Mi
