apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: stirling-pdf
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    requests.storage: 10Gi
    persistentvolumeclaims: "5"
    pods: "10"
