apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway

resources:
  - namespace.yaml
  # renovate: depName=kubernetes-sigs/gateway-api
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.1/standard-install.yaml
  - gateway.yaml
  - certificate.yaml
  - http-redirect-route.yaml
