apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/urosevicvuk/ykube
        revision: main
        directories:
          - path: apps/infrastructure/*
  template:
    metadata:
      name: 'infrastructure-{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "20"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/urosevicvuk/ykube
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
