apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: morel
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/urosevicvuk/ykube
        revision: main
        directories:
          - path: apps/morel/*
  template:
    metadata:
      name: 'morel-{{path.basename}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: morel
      source:
        repoURL: https://github.com/urosevicvuk/ykube
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: morel
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          # Apps own their Namespace resource.
          - ServerSideApply=true
          - PruneLast=true
