apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: raf-external
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: banka
            repoURL: https://github.com/RAF-SI-2025/Banka-3-Infrastructure
            targetRevision: v0.7.2
            path: .
  template:
    metadata:
      name: 'raf-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: raf
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        # Convention: name banka → namespace raf-banka.
        namespace: 'raf-{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - PruneLast=true
