apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-pg
  namespace: authelia
spec:
  instances: 1
  storage:
    storageClass: longhorn
    size: 2Gi
  bootstrap:
    initdb:
      database: authelia
      owner: authelia
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
