apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-db-credentials-cnpg
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authelia-db-credentials-cnpg
  data:
    - secretKey: password
      remoteRef:
        key: secret/cloudnative-pg/authelia
        property: password
    - secretKey: username
      remoteRef:
        key: secret/cloudnative-pg/authelia
        property: username
