apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor

resources:
  - namespace.yaml
  - cnpg-cluster.yaml
  - secrets.yaml
  - httproute.yaml

helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    version: 1.16.0  # renovate: depName=goharbor/harbor
    releaseName: harbor
    namespace: harbor
    valuesFile: values.yaml
    includeCRDs: true
