apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sloth

resources:
  - namespace.yaml

helmCharts:
  - name: sloth
    repo: https://slok.github.io/sloth
    version: 0.11.0  # renovate: depName=slok/sloth
    releaseName: sloth
    namespace: sloth
    valuesFile: values.yaml
    includeCRDs: true
